# Generated by Django 5.1.6 on 2025-03-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnserverappV1', '0002_uploadedmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedmodel',
            name='file',
            field=models.FileField(upload_to='upload_model/'),
        ),
    ]
