# Generated by Django 4.2.16 on 2025-04-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnserverappV1', '0003_alter_uploadedmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedmodel',
            name='name',
            field=models.CharField(default='Unnamed Network', max_length=200),
        ),
    ]
