# Generated by Django 4.2.16 on 2025-06-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnserverappV1', '0005_questionnaire_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
